### ISSUE TITLE
Data sets for reproducibility

### ISSUE THREAD

**Issue by pmla** [mfulford/DeepIce#1]
Could you upload the data sets here, or provide a link to them?  This would be great for reproducibility.  I am most interested in the simulation slab with 5760 molecules, but the training data and pre-trained weights would be nice too.

**Comment by mfulford** [comment]
Hi 
I've just uploaded a sample of the training and test sets with 100k examples in each. You can load it using deepice.get_data(filename ='...', test=True/False, train=False/True). I'm working on putting the full data sets somewhere else as it's too large for GitHub. 
I've also uploaded the weights for models trained on the rotated and unrotated/normal data sets. All of these can be found in /data. At some point in the next week or so I'll upload the simulation slab with 5760 molecules - will post here once I have. 
Best wishes
Max

**Comment by pmla** [comment]
Thanks Max.  That will be great.
Best regards,
Peter

**Comment by mfulford** [comment]
Hi Peter
I've uploaded the slab trajectory into the /data  (Trajectory_surfX_tip4p_270K_id420_Oatoms.dcd) along with the structure pdb file. The method slab_import_writecsv in scripts/input_methods.py can be used to convert the dcd into a csv input for deepice.
Best wishes
Max

**Comment by pmla** [comment]
Thanks Max.  That is great.
