### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by ribeiro-ingrid** [mfulford/DeepIce#2]
Which version of Keras and TensorFlow was used?

I tried Python 3.7.4, Keras 2.2.4 and TensorFlow 2.0.0 and I got 
AttributeError: module 'keras.backend' has no attribute 'tf'
if I fix this one (by changing K.tf. to K.), there are other errors which seems to be related to compatibility issues.

**Comment by mfulford** [comment]
I think you have an issue with your keras installation. Try:
pip uninstall keras
pip install keras --upgrade

**Comment by ribeiro-ingrid** [comment]
Thanks for your reply. In fact, I tried different old versions, and

pip install tensorflow==1.5.0
pip install keras==2.0.9

worked for me.
